<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>plantroid_launch</name>
  <version>1.0.0</version>
  <description>Dummy package that collects all of the launch files for Social Plantroid</description>
  <maintainer email="antonio@mizuuchi.lab.tuat.ac.jp">Antono Galiza Cerdeira Gonzalez</maintainer>
  <license>Apache License 2.0</license>

  <depend>rclpy</depend>
  <depend>speech_recogntion</depend>
  <depend>uuid</depend>
  <depend>opencv-python</depend>
  <depend>tensorflow</depend>
  <depend>plantroid_busy</depend>
  <depend>plantroid_encoder</depend>
  <depend>plantroid_gestures</depend>
  <depend>plantroid_gui</depend>
  <depend>plantroid_listener</depend>
  <depend>plantroid_msgs</depend>
  <depend>plantroid_navigation</depend>
  <depend>plantroid_neck</depend>
  <depend>plantroid_sensors</depend>
  <depend>plantroid_social</depend>
  <depend>plantroid_vision</depend>

  <!--depend>plant_model</depend>
  <!depend>plantroid_memory</depend-->

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
