"""LangChain chains for intent classification and response generation.

No hardcoded responses - everything goes through the LLM.
Uses DuckDuckGo for web search (free, no API key).

Supports both Ollama and LM Studio backends.
"""

from typing import Optional, Literal

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_community.tools import DuckDuckGoSearchRun

from .prompts import (
    INTENT_CLASSIFICATION_PROMPT,
    RESPONSE_GENERATION_PROMPT,
    EMOTION_DETECTION_PROMPT,
    ROBOT_PERSONA,
    BUSY_RESPONSE_PROMPT,
    PROBLEM_ANNOUNCEMENT_PROMPT,
    format_notifications,
    USER_RESPONSE_CLASSIFICATION_PROMPT,
    SENSOR_INTEGRATED_RESPONSE_PROMPT,
    DEFERRED_RESPONSE_PROMPT,
    IMPROVEMENT_CELEBRATION_PROMPT,
)
from .state import Intent, Emotion, RobotStatus
from .sensor_tracker import UserResponseType, SensorType, THRESHOLDS
from .solutions import get_solutions, get_quick_fix


# Default settings
DEFAULT_MODEL = "qwen2:0.5b"  # For Ollama
DEFAULT_OLLAMA_URL = "http://localhost:11434"
DEFAULT_LMSTUDIO_URL = "http://localhost:1234/v1"

# Backend types
BackendType = Literal["ollama", "lmstudio"]


def create_llm(
    backend: BackendType = "ollama",
    model_name: str = DEFAULT_MODEL,
    base_url: Optional[str] = None,
    temperature: float = 0.7,
):
    """Create an LLM instance for the specified backend.

    Args:
        backend: "ollama" or "lmstudio"
        model_name: Model name (for Ollama) or ignored for LM Studio (uses loaded model)
        base_url: Server URL (auto-detected if None)
        temperature: Generation temperature

    Returns:
        LangChain chat model instance
    """
    if backend == "lmstudio":
        from langchain_openai import ChatOpenAI

        url = base_url or DEFAULT_LMSTUDIO_URL
        # LM Studio uses OpenAI-compatible API
        # Model name can be anything - LM Studio uses the currently loaded model
        return ChatOpenAI(
            base_url=url,
            api_key="lm-studio",  # LM Studio doesn't require a real key
            model=model_name or "local-model",
            temperature=temperature,
        )
    else:
        # Default to Ollama
        from langchain_ollama import ChatOllama

        url = base_url or DEFAULT_OLLAMA_URL
        return ChatOllama(
            model=model_name,
            base_url=url,
            temperature=temperature,
        )


class DialogueChains:
    """LangChain chains for the dialogue system.

    All responses are generated by the LLM - no hardcoded flows.
    Supports both Ollama and LM Studio backends.
    """

    def __init__(
        self,
        model_name: str = DEFAULT_MODEL,
        base_url: Optional[str] = None,
        backend: BackendType = "ollama",
    ):
        """Initialize chains with LLM backend.

        Args:
            model_name: Model name (for Ollama; LM Studio uses loaded model)
            base_url: Server URL (auto-detected based on backend if None)
            backend: "ollama" or "lmstudio"
        """
        self.model_name = model_name
        self.backend = backend
        self.base_url = base_url

        self.llm = create_llm(
            backend=backend,
            model_name=model_name,
            base_url=base_url,
            temperature=0.7,
        )

        # DuckDuckGo search tool (free, no API key)
        self.search_tool = DuckDuckGoSearchRun()

        self._setup_chains()

    def _setup_chains(self):
        """Set up the LangChain chains."""
        # Intent classification chain
        intent_prompt = ChatPromptTemplate.from_template(INTENT_CLASSIFICATION_PROMPT)
        self.intent_chain = intent_prompt | self.llm | StrOutputParser()

        # Response generation chain
        response_prompt = ChatPromptTemplate.from_messages([
            ("system", ROBOT_PERSONA),
            ("human", RESPONSE_GENERATION_PROMPT),
        ])
        self.response_chain = response_prompt | self.llm | StrOutputParser()

        # Emotion detection chain
        emotion_prompt = ChatPromptTemplate.from_template(EMOTION_DETECTION_PROMPT)
        self.emotion_chain = emotion_prompt | self.llm | StrOutputParser()

        # Busy response chain
        busy_prompt = ChatPromptTemplate.from_template(BUSY_RESPONSE_PROMPT)
        self.busy_chain = busy_prompt | self.llm | StrOutputParser()

        # Problem announcement chain
        problem_prompt = ChatPromptTemplate.from_template(PROBLEM_ANNOUNCEMENT_PROMPT)
        self.problem_chain = problem_prompt | self.llm | StrOutputParser()

        # User response classification chain
        user_response_prompt = ChatPromptTemplate.from_template(USER_RESPONSE_CLASSIFICATION_PROMPT)
        self.user_response_chain = user_response_prompt | self.llm | StrOutputParser()

        # Sensor integrated response chain
        sensor_response_prompt = ChatPromptTemplate.from_template(SENSOR_INTEGRATED_RESPONSE_PROMPT)
        self.sensor_response_chain = sensor_response_prompt | self.llm | StrOutputParser()

        # Deferred response chain
        deferred_prompt = ChatPromptTemplate.from_template(DEFERRED_RESPONSE_PROMPT)
        self.deferred_chain = deferred_prompt | self.llm | StrOutputParser()

        # Celebration chain
        celebration_prompt = ChatPromptTemplate.from_template(IMPROVEMENT_CELEBRATION_PROMPT)
        self.celebration_chain = celebration_prompt | self.llm | StrOutputParser()

    def classify_intent(self, message: str) -> str:
        """Classify the intent of a user message using LLM.

        Args:
            message: User's message

        Returns:
            Intent category string
        """
        try:
            result = self.intent_chain.invoke({"message": message})
            intent = result.strip().lower()

            # Map to valid intent
            valid_intents = [i.value for i in Intent]
            if intent in valid_intents:
                return intent

            # Fuzzy matching
            if any(g in intent for g in ["greet", "hello", "hi"]):
                return Intent.GREETING.value
            if any(f in intent for f in ["farewell", "bye", "goodbye", "quit"]):
                return Intent.FAREWELL.value
            if any(q in intent for q in ["question", "ask", "what", "who", "how", "search"]):
                return Intent.QUESTION.value
            if any(a in intent for a in ["acknowledge", "yes", "no", "ok"]):
                return Intent.ACKNOWLEDGMENT.value

            return Intent.GENERAL.value

        except Exception as e:
            print(f"Intent classification error: {e}")
            return Intent.GENERAL.value

    def search_web(self, query: str) -> str:
        """Search the web using DuckDuckGo.

        Args:
            query: Search query

        Returns:
            Search results as string
        """
        try:
            results = self.search_tool.invoke(query)
            return results
        except Exception as e:
            print(f"Search error: {e}")
            return f"I couldn't search for that right now."

    def generate_response(
        self,
        message: str,
        emotion: str = "neutral",
        history: Optional[list] = None,
        search_context: Optional[str] = None,
    ) -> str:
        """Generate a response using LLM.

        Args:
            message: User's message
            emotion: User's detected emotion
            history: Conversation history list
            search_context: Optional search results to include

        Returns:
            Robot's response text
        """
        try:
            # Format history
            history_str = ""
            if history:
                for role, msg in history[-5:]:  # Last 5 turns
                    history_str += f"{role}: {msg}\n"

            # Add search context if available
            context_str = ""
            if search_context:
                context_str = f"\n\nRelevant information from web search:\n{search_context}\n"

            result = self.response_chain.invoke({
                "message": message + context_str,
                "emotion": emotion,
                "history": history_str or "No previous conversation.",
            })
            return result.strip()

        except Exception as e:
            print(f"Response generation error: {e}")
            return "I'm having trouble responding right now."

    def detect_emotion(self, user_message: str, robot_response: str) -> str:
        """Detect the appropriate emotion using LLM.

        Args:
            user_message: What the user said
            robot_response: What the robot will say

        Returns:
            Emotion string
        """
        try:
            result = self.emotion_chain.invoke({
                "user_message": user_message,
                "robot_response": robot_response,
            })
            emotion = result.strip().lower()

            # Validate emotion
            valid_emotions = [e.value for e in Emotion]
            if emotion in valid_emotions:
                return emotion

            # Fuzzy match
            if "happ" in emotion or "joy" in emotion:
                return Emotion.HAPPY.value
            if "sad" in emotion:
                return Emotion.SAD.value
            if "ang" in emotion:
                return Emotion.ANGER.value
            if "surpr" in emotion:
                return Emotion.SURPRISE.value

            return Emotion.NEUTRAL.value

        except Exception as e:
            print(f"Emotion detection error: {e}")
            return Emotion.NEUTRAL.value

    def should_search(self, message: str, intent: str) -> bool:
        """Determine if web search is needed.

        Args:
            message: User's message
            intent: Classified intent

        Returns:
            True if search should be performed
        """
        # Search for questions about facts, people, things
        if intent == Intent.QUESTION.value:
            search_triggers = [
                "what is", "who is", "who was", "what was",
                "tell me about", "search for", "look up",
                "find", "how to", "where is", "when did",
            ]
            msg_lower = message.lower()
            return any(trigger in msg_lower for trigger in search_triggers)
        return False

    def generate_busy_response(self, message: str) -> str:
        """Generate a response when robot is busy.

        Args:
            message: User's message

        Returns:
            Busy response text
        """
        try:
            result = self.busy_chain.invoke({"message": message})
            return result.strip()
        except Exception as e:
            print(f"Busy response generation error: {e}")
            return "I'm sorry, I'm currently busy with a task. Please wait a moment."

    def generate_problem_response(self, message: str, notifications: dict) -> str:
        """Generate a response announcing problems/notifications.

        Args:
            message: User's message
            notifications: Dict of {sensor_name: [level, priority, ...]}

        Returns:
            Problem announcement text
        """
        try:
            problems_text = format_notifications(notifications)
            result = self.problem_chain.invoke({
                "message": message,
                "problems": problems_text,
            })
            return result.strip()
        except Exception as e:
            print(f"Problem response generation error: {e}")
            return "I've detected some issues with the soil that need attention."

    def determine_robot_status(
        self,
        robot_busy: bool,
        notifications: dict,
    ) -> str:
        """Determine the robot's current status.

        Args:
            robot_busy: Whether robot is busy with a task
            notifications: Pending sensor notifications

        Returns:
            RobotStatus value: "free", "busy", or "problem"
        """
        if robot_busy:
            return RobotStatus.BUSY.value
        elif notifications:
            return RobotStatus.PROBLEM.value
        else:
            return RobotStatus.FREE.value

    def classify_user_response(self, message: str, issue_description: str) -> UserResponseType:
        """Classify user's response to a sensor issue.

        Args:
            message: User's message
            issue_description: Description of the issue that was mentioned

        Returns:
            UserResponseType enum value
        """
        try:
            result = self.user_response_chain.invoke({
                "message": message,
                "issue_description": issue_description,
            })
            response = result.strip().lower()

            # Map to enum
            mapping = {
                "committed": UserResponseType.COMMITTED,
                "deferred": UserResponseType.DEFERRED,
                "rejected": UserResponseType.REJECTED,
                "question": UserResponseType.QUESTION,
                "unrelated": UserResponseType.UNRELATED,
            }
            return mapping.get(response, UserResponseType.UNRELATED)
        except Exception as e:
            print(f"User response classification error: {e}")
            return UserResponseType.UNRELATED

    def generate_sensor_integrated_response(
        self,
        base_response: str,
        issue: dict,
        solution: dict,
    ) -> str:
        """Generate response that naturally integrates sensor issue.

        Args:
            base_response: The original response to the user
            issue: Dict with sensor issue details
            solution: Dict with solution details

        Returns:
            Combined response with sensor information
        """
        try:
            sensor_type = SensorType(issue["sensor_type"])
            threshold = THRESHOLDS[sensor_type]

            result = self.sensor_response_chain.invoke({
                "base_response": base_response,
                "sensor_type": issue["sensor_type"],
                "value": issue["current_value"],
                "unit": threshold.unit,
                "optimal_min": threshold.optimal_min,
                "optimal_max": threshold.optimal_max,
                "direction": "too low" if issue["direction"] == "too_low" else "too high",
                "severity": issue["severity"],
                "action": solution["action"] if solution else "check on it",
                "outcome": f"get it back to optimal levels ({threshold.optimal_min}-{threshold.optimal_max}{threshold.unit})",
            })
            return result.strip()
        except Exception as e:
            print(f"Sensor integrated response error: {e}")
            return base_response

    def generate_deferred_response(
        self,
        message: str,
        issue: dict,
        quick_fix: dict,
    ) -> str:
        """Generate empathetic response when user defers action.

        Args:
            message: User's message
            issue: Dict with sensor issue details
            quick_fix: Dict with quick fix solution details

        Returns:
            Empathetic response suggesting quick fix
        """
        try:
            sensor_type = SensorType(issue["sensor_type"])
            threshold = THRESHOLDS[sensor_type]

            result = self.deferred_chain.invoke({
                "sensor_type": issue["sensor_type"],
                "value": issue["current_value"],
                "unit": threshold.unit,
                "optimal_min": threshold.optimal_min,
                "optimal_max": threshold.optimal_max,
                "message": message,
                "time_until_damage": quick_fix["time_until_damage"] if quick_fix else "soon",
                "quick_fix_action": quick_fix["action"] if quick_fix else "a quick check",
            })
            return result.strip()
        except Exception as e:
            print(f"Deferred response error: {e}")
            return "I understand. Just keep an eye on it when you can."

    def generate_celebration_response(
        self,
        base_response: str,
        sensor_type: str,
        previous_value: float,
        current_value: float,
    ) -> str:
        """Generate happy response for resolved issue.

        Args:
            base_response: The original response to the user
            sensor_type: Type of sensor that improved
            previous_value: Previous sensor value
            current_value: Current (improved) sensor value

        Returns:
            Celebratory response
        """
        try:
            result = self.celebration_chain.invoke({
                "base_response": base_response,
                "sensor_type": sensor_type,
                "previous_value": previous_value,
                "current_value": current_value,
            })
            return result.strip()
        except Exception as e:
            print(f"Celebration response error: {e}")
            return base_response
