"""LangChain chains for intent classification and response generation.

No hardcoded responses - everything goes through the LLM.
Uses DuckDuckGo for web search (free, no API key).

Supports both Ollama and LM Studio backends.
"""

from typing import Optional, Literal

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_community.tools import DuckDuckGoSearchRun

from .prompts import (
    INTENT_CLASSIFICATION_PROMPT,
    RESPONSE_GENERATION_PROMPT,
    EMOTION_DETECTION_PROMPT,
    ROBOT_PERSONA,
)
from .state import Intent, Emotion


# Default settings
DEFAULT_MODEL = "qwen2:0.5b"  # For Ollama
DEFAULT_OLLAMA_URL = "http://localhost:11434"
DEFAULT_LMSTUDIO_URL = "http://localhost:1234/v1"

# Backend types
BackendType = Literal["ollama", "lmstudio"]


def create_llm(
    backend: BackendType = "ollama",
    model_name: str = DEFAULT_MODEL,
    base_url: Optional[str] = None,
    temperature: float = 0.7,
):
    """Create an LLM instance for the specified backend.

    Args:
        backend: "ollama" or "lmstudio"
        model_name: Model name (for Ollama) or ignored for LM Studio (uses loaded model)
        base_url: Server URL (auto-detected if None)
        temperature: Generation temperature

    Returns:
        LangChain chat model instance
    """
    if backend == "lmstudio":
        from langchain_openai import ChatOpenAI

        url = base_url or DEFAULT_LMSTUDIO_URL
        # LM Studio uses OpenAI-compatible API
        # Model name can be anything - LM Studio uses the currently loaded model
        return ChatOpenAI(
            base_url=url,
            api_key="lm-studio",  # LM Studio doesn't require a real key
            model=model_name or "local-model",
            temperature=temperature,
        )
    else:
        # Default to Ollama
        from langchain_ollama import ChatOllama

        url = base_url or DEFAULT_OLLAMA_URL
        return ChatOllama(
            model=model_name,
            base_url=url,
            temperature=temperature,
        )


class DialogueChains:
    """LangChain chains for the dialogue system.

    All responses are generated by the LLM - no hardcoded flows.
    Supports both Ollama and LM Studio backends.
    """

    def __init__(
        self,
        model_name: str = DEFAULT_MODEL,
        base_url: Optional[str] = None,
        backend: BackendType = "ollama",
    ):
        """Initialize chains with LLM backend.

        Args:
            model_name: Model name (for Ollama; LM Studio uses loaded model)
            base_url: Server URL (auto-detected based on backend if None)
            backend: "ollama" or "lmstudio"
        """
        self.model_name = model_name
        self.backend = backend
        self.base_url = base_url

        self.llm = create_llm(
            backend=backend,
            model_name=model_name,
            base_url=base_url,
            temperature=0.7,
        )

        # DuckDuckGo search tool (free, no API key)
        self.search_tool = DuckDuckGoSearchRun()

        self._setup_chains()

    def _setup_chains(self):
        """Set up the LangChain chains."""
        # Intent classification chain
        intent_prompt = ChatPromptTemplate.from_template(INTENT_CLASSIFICATION_PROMPT)
        self.intent_chain = intent_prompt | self.llm | StrOutputParser()

        # Response generation chain
        response_prompt = ChatPromptTemplate.from_messages([
            ("system", ROBOT_PERSONA),
            ("human", RESPONSE_GENERATION_PROMPT),
        ])
        self.response_chain = response_prompt | self.llm | StrOutputParser()

        # Emotion detection chain
        emotion_prompt = ChatPromptTemplate.from_template(EMOTION_DETECTION_PROMPT)
        self.emotion_chain = emotion_prompt | self.llm | StrOutputParser()

    def classify_intent(self, message: str) -> str:
        """Classify the intent of a user message using LLM.

        Args:
            message: User's message

        Returns:
            Intent category string
        """
        try:
            result = self.intent_chain.invoke({"message": message})
            intent = result.strip().lower()

            # Map to valid intent
            valid_intents = [i.value for i in Intent]
            if intent in valid_intents:
                return intent

            # Fuzzy matching
            if any(g in intent for g in ["greet", "hello", "hi"]):
                return Intent.GREETING.value
            if any(f in intent for f in ["farewell", "bye", "goodbye", "quit"]):
                return Intent.FAREWELL.value
            if any(q in intent for q in ["question", "ask", "what", "who", "how", "search"]):
                return Intent.QUESTION.value
            if any(a in intent for a in ["acknowledge", "yes", "no", "ok"]):
                return Intent.ACKNOWLEDGMENT.value

            return Intent.GENERAL.value

        except Exception as e:
            print(f"Intent classification error: {e}")
            return Intent.GENERAL.value

    def search_web(self, query: str) -> str:
        """Search the web using DuckDuckGo.

        Args:
            query: Search query

        Returns:
            Search results as string
        """
        try:
            results = self.search_tool.invoke(query)
            return results
        except Exception as e:
            print(f"Search error: {e}")
            return f"I couldn't search for that right now."

    def generate_response(
        self,
        message: str,
        emotion: str = "neutral",
        history: Optional[list] = None,
        search_context: Optional[str] = None,
    ) -> str:
        """Generate a response using LLM.

        Args:
            message: User's message
            emotion: User's detected emotion
            history: Conversation history list
            search_context: Optional search results to include

        Returns:
            Robot's response text
        """
        try:
            # Format history
            history_str = ""
            if history:
                for role, msg in history[-5:]:  # Last 5 turns
                    history_str += f"{role}: {msg}\n"

            # Add search context if available
            context_str = ""
            if search_context:
                context_str = f"\n\nRelevant information from web search:\n{search_context}\n"

            result = self.response_chain.invoke({
                "message": message + context_str,
                "emotion": emotion,
                "history": history_str or "No previous conversation.",
            })
            return result.strip()

        except Exception as e:
            print(f"Response generation error: {e}")
            return "I'm having trouble responding right now."

    def detect_emotion(self, user_message: str, robot_response: str) -> str:
        """Detect the appropriate emotion using LLM.

        Args:
            user_message: What the user said
            robot_response: What the robot will say

        Returns:
            Emotion string
        """
        try:
            result = self.emotion_chain.invoke({
                "user_message": user_message,
                "robot_response": robot_response,
            })
            emotion = result.strip().lower()

            # Validate emotion
            valid_emotions = [e.value for e in Emotion]
            if emotion in valid_emotions:
                return emotion

            # Fuzzy match
            if "happ" in emotion or "joy" in emotion:
                return Emotion.HAPPY.value
            if "sad" in emotion:
                return Emotion.SAD.value
            if "ang" in emotion:
                return Emotion.ANGER.value
            if "surpr" in emotion:
                return Emotion.SURPRISE.value

            return Emotion.NEUTRAL.value

        except Exception as e:
            print(f"Emotion detection error: {e}")
            return Emotion.NEUTRAL.value

    def should_search(self, message: str, intent: str) -> bool:
        """Determine if web search is needed.

        Args:
            message: User's message
            intent: Classified intent

        Returns:
            True if search should be performed
        """
        # Search for questions about facts, people, things
        if intent == Intent.QUESTION.value:
            search_triggers = [
                "what is", "who is", "who was", "what was",
                "tell me about", "search for", "look up",
                "find", "how to", "where is", "when did",
            ]
            msg_lower = message.lower()
            return any(trigger in msg_lower for trigger in search_triggers)
        return False
