"""LangGraph dialogue flow definition.

No hardcoded responses - all responses generated by LLM.
Includes DuckDuckGo web search for factual questions.
"""

from typing import Literal
from langgraph.graph import StateGraph, END

from .state import DialogueState, Intent, get_prosody_for_emotion
from .chains import DialogueChains


# Global chains instance (initialized lazily)
_chains: DialogueChains = None


def get_chains() -> DialogueChains:
    """Get or create the dialogue chains instance."""
    global _chains
    if _chains is None:
        _chains = DialogueChains()
    return _chains


def set_chains(chains: DialogueChains):
    """Set the dialogue chains instance (for testing/custom config)."""
    global _chains
    _chains = chains


# ============================================================================
# Graph Nodes - All use LLM, no hardcoded responses
# ============================================================================

def classify_intent_node(state: DialogueState) -> DialogueState:
    """Classify the intent of the user's message using LLM."""
    chains = get_chains()
    message = state.get("human_message", "")

    # LLM classifies intent
    intent = chains.classify_intent(message)

    return {**state, "intent": intent}


def check_search_node(state: DialogueState) -> DialogueState:
    """Check if web search is needed and perform it."""
    chains = get_chains()

    message = state.get("human_message", "")
    intent = state.get("intent", Intent.GENERAL.value)

    search_context = None

    # Check if we should search
    if chains.should_search(message, intent):
        # Extract search query from message
        search_context = chains.search_web(message)

    return {**state, "search_context": search_context}


def generate_response_node(state: DialogueState) -> DialogueState:
    """Generate a response using LLM (no hardcoded responses)."""
    chains = get_chains()

    message = state.get("human_message", "")
    voice_emotion = state.get("voice_emotion", "neutral")
    history = state.get("conversation_history", [])
    search_context = state.get("search_context")

    # Always use LLM to generate response
    response = chains.generate_response(
        message=message,
        emotion=voice_emotion,
        history=history,
        search_context=search_context,
    )

    return {**state, "response": response}


def determine_emotion_node(state: DialogueState) -> DialogueState:
    """Determine the robot's emotional response using LLM."""
    chains = get_chains()

    message = state.get("human_message", "")
    response = state.get("response", "")

    # LLM determines appropriate emotion
    emotion = chains.detect_emotion(message, response)

    # Get prosody for the emotion
    prosody = get_prosody_for_emotion(emotion)

    return {**state, "response_emotion": emotion, "prosody": prosody}


def update_history_node(state: DialogueState) -> DialogueState:
    """Update conversation history with the exchange."""
    history = state.get("conversation_history", [])
    message = state.get("human_message", "")
    response = state.get("response", "")

    # Add this exchange to history
    history = list(history)  # Copy to avoid mutation
    history.append(("Human", message))
    history.append(("Plantroid", response))

    # Keep only last 10 turns (5 exchanges)
    if len(history) > 10:
        history = history[-10:]

    return {**state, "conversation_history": history}


# ============================================================================
# Conditional Edges
# ============================================================================

def route_after_intent(state: DialogueState) -> Literal["search", "respond"]:
    """Route based on whether search is needed."""
    chains = get_chains()
    message = state.get("human_message", "")
    intent = state.get("intent", "")

    if chains.should_search(message, intent):
        return "search"
    return "respond"


# ============================================================================
# Graph Builder
# ============================================================================

def build_dialogue_graph() -> StateGraph:
    """Build and compile the dialogue graph.

    Graph flow:
    START -> classify_intent -> [search?] -> generate_response -> determine_emotion -> update_history -> END

    All nodes use LLM - no hardcoded responses.

    Returns:
        Compiled StateGraph
    """
    # Create graph
    graph = StateGraph(DialogueState)

    # Add nodes
    graph.add_node("classify_intent", classify_intent_node)
    graph.add_node("check_search", check_search_node)
    graph.add_node("generate_response", generate_response_node)
    graph.add_node("determine_emotion", determine_emotion_node)
    graph.add_node("update_history", update_history_node)

    # Set entry point
    graph.set_entry_point("classify_intent")

    # Add edges
    graph.add_edge("classify_intent", "check_search")
    graph.add_edge("check_search", "generate_response")
    graph.add_edge("generate_response", "determine_emotion")
    graph.add_edge("determine_emotion", "update_history")
    graph.add_edge("update_history", END)

    # Compile and return
    return graph.compile()


def process_message(
    message: str,
    voice_emotion: str = "neutral",
    history: list = None,
    robot_busy: bool = False,
    notifications: dict = None,
) -> DialogueState:
    """Process a user message through the dialogue graph.

    This is the main entry point for the dialogue system.
    All responses are generated by LLM - no hardcoded flows.

    Args:
        message: User's message text
        voice_emotion: Emotion detected from voice
        history: Previous conversation history
        robot_busy: Whether robot is currently busy
        notifications: Pending sensor notifications

    Returns:
        Final dialogue state with response
    """
    # Build initial state
    initial_state: DialogueState = {
        "human_message": message,
        "voice_emotion": voice_emotion,
        "conversation_history": history or [],
        "robot_busy": robot_busy,
        "has_problem": bool(notifications),
        "notifications": notifications or {},
        "search_context": None,
    }

    # Get or build graph
    graph = build_dialogue_graph()

    # Run graph
    final_state = graph.invoke(initial_state)

    return final_state
